### ISSUE TITLE
サイトマップをつくる

### ISSUE THREAD

**Issue by truthNH** [Ranyuen/web#106]
どうやって実装しようか

**Comment by ne-sachirou** [comment]
GoogleやBingむけのものですよね。やらない、といふ選択も合理的でせう。

**Comment by truthNH** [comment]
社長がサイト内にナビゲーションとしてサイトマップが欲しいそうです

**Comment by ne-sachirou** [comment]
ぢゃあ config/nav.xml から生成すればいいんぢゃないでせうか。

**Comment by truthNH** [comment]
なるほど、やってみます。

**Comment by truthNH** [comment]
実装済み

**Comment by truthNH** [comment]
新しい記事を追加すると自動でsitemap.xmlを作成
