### ISSUE TITLE
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Database does not exist.' in C:\Users\kama.yosuke\ranyuen\web\vendor\illuminate\database\Illuminate\Database\Connectors\SQLiteConnector.php on line 32

### ISSUE THREAD

**Issue by midoribito** [Ranyuen/web#92]
InvalidArgumentException: Database does not exist. in C:\Users\kama.yosuke\ranyuen\web\vendor\illuminate\database\Illuminate\Database\Connectors\SQLiteConnector.php on line 32

**Comment by ne-sachirou** [comment]
db.sqlite3 ファイルが無かったからというてエラーを出すな、ファイルくらい自動でつくれ、といふissueですね。

**Comment by truthNH** [comment]
開発環境のDBをMySQLに統一したのでクローズ
